// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@1.0.0";

// src/lib/mcp/tools/append-idea-chat.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function callFunction(ctx, name, body) {
  const token = ctx.getToken();
  if (!token) throw new Error("callFunction requires a verified OAuth token");
  const res = await fetch(`${supabaseProjectUrl()}/functions/v1/${name}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
      apikey: supabasePublishableKey()
    },
    body: JSON.stringify(body)
  });
  const json = await res.json().catch(() => ({}));
  if (!res.ok) {
    throw new Error(String(json?.error ?? `${name} failed (${res.status})`));
  }
  return json;
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) throw new Error("Not authenticated");
  const userId = ctx.getUserId();
  if (!userId) throw new Error("Not authenticated");
  return userId;
}
var textResult = (text) => ({ content: [{ type: "text", text }] });
var jsonResult = (data) => ({
  content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
  structuredContent: data
});
var errorResult = (message) => ({
  content: [{ type: "text", text: message }],
  isError: true
});

// src/lib/mcp/tools/append-idea-chat.ts
var append_idea_chat_default = defineTool({
  name: "append_idea_chat",
  title: "Append to idea brainstorm",
  description: "Append a message to an idea's brainstorm thread so the conversation you are having shows up inside the app next to that idea.",
  inputSchema: {
    idea_id: z.string().uuid(),
    role: z.enum(["user", "assistant"]),
    content: z.string().trim().min(1).max(2e4)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ idea_id, role, content }, ctx) => {
    try {
      const userId = requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const { data, error } = await supabase.from("idea_chats").insert({ user_id: userId, idea_id, role, content }).select("id, role, created_at").maybeSingle();
      if (error) return errorResult(error.message);
      return jsonResult({ message: data });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "Append failed");
    }
  }
});

// src/lib/mcp/tools/build-prompt.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z2 } from "npm:zod@^3.25.76";
var CONTEXT_LIMIT = 6;
var CONTEXT_CHARS_EACH = 900;
var STOPWORDS = /* @__PURE__ */ new Set([
  "a",
  "an",
  "and",
  "are",
  "as",
  "at",
  "be",
  "by",
  "for",
  "from",
  "how",
  "in",
  "into",
  "is",
  "it",
  "of",
  "on",
  "or",
  "that",
  "the",
  "this",
  "to",
  "using",
  "what",
  "when",
  "why",
  "with",
  "your"
]);
function titleTerms(title, max = 6) {
  return [
    ...new Set(
      title.toLowerCase().replace(/[^a-z0-9\s]/g, " ").split(/\s+/).filter((w) => w.length > 2 && !STOPWORDS.has(w))
    )
  ].slice(0, max);
}
function renderContext(rows) {
  return rows.map((r) => {
    const body = (r.ai_summary ?? r.raw_note ?? "").trim().slice(0, CONTEXT_CHARS_EACH);
    const tags = r.tags?.length ? ` [${r.tags.join(", ")}]` : "";
    return body ? `- ${r.title}${tags}: ${body}` : `- ${r.title}${tags}`;
  }).join("\n");
}
var build_prompt_default = defineTool2({
  name: "build_prompt",
  title: "Build a prompt or build brief from a saved idea",
  description: "Turn a saved idea \u2014 including a captured reel, video or article transcript \u2014 into something the calling agent can act on. mode 'build' returns a build brief written for an agent that has the user's project open: mechanism, ordered steps, how to adapt it to their stack, how to verify it, and what not to do. mode 'paste' returns a short prompt for a human to paste into a chat. Pulls in neighbouring saved ideas for continuity. Returns the text without saving anything.",
  inputSchema: {
    idea_id: z2.string().uuid().describe("The saved idea to build from. Find it with search_ideas."),
    goal: z2.string().trim().max(2e3).optional().describe(
      "What the user wants out of it \u2014 'build an MVP', 'write a spec', 'turn this into a landing page'. Steers the output; leave empty for a general-purpose one."
    ),
    mode: z2.enum(["build", "paste"]).optional().describe(
      "'build' (default) for a brief you are going to act on yourself. 'paste' for a short prompt the user will paste into a chat elsewhere."
    ),
    stack: z2.string().trim().max(2e3).optional().describe(
      "The project you have open \u2014 language, framework, hosting, notable constraints. Supply this whenever you know it; the brief is adapted to it, and without it the brief has to guess."
    ),
    use_context: z2.boolean().optional().describe(
      "Include neighbouring saved ideas (same folder, then shared tags) so the brief builds on what the user already decided. Default true."
    )
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ idea_id, goal, mode, stack, use_context }, ctx) => {
    try {
      requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const { data, error } = await supabase.from("ideas").select(
        "title, raw_note, ai_summary, extracted_text, source_url, source_label, folder_id, tags"
      ).eq("id", idea_id).is("deleted_at", null).maybeSingle();
      if (error) return errorResult(error.message);
      if (!data) return errorResult("No such idea, or it is in the Trash.");
      let neighbours = [];
      if (use_context !== false) {
        const base = () => supabase.from("ideas").select("id, title, ai_summary, raw_note, tags").is("deleted_at", null).neq("id", idea_id).order("updated_at", { ascending: false }).limit(CONTEXT_LIMIT);
        if (data.folder_id) {
          const { data: rows } = await base().eq("folder_id", data.folder_id);
          neighbours = rows ?? [];
        }
        if (neighbours.length === 0 && data.tags?.length) {
          const { data: rows } = await base().overlaps("tags", data.tags);
          neighbours = rows ?? [];
        }
        if (neighbours.length === 0) {
          const terms2 = titleTerms(data.title);
          if (terms2.length) {
            const { data: rows } = await base().textSearch(
              "search_vector",
              terms2.join(" OR "),
              { type: "websearch" }
            );
            neighbours = rows ?? [];
          }
        }
      }
      const note = [data.raw_note ?? "", goal ? `Goal: ${goal}` : ""].filter(Boolean).join("\n\n");
      const res = await callFunction(ctx, "generate-prompt", {
        title: data.title,
        note,
        summary: data.ai_summary,
        extractedText: data.extracted_text,
        sourceUrl: data.source_url,
        sourceLabel: data.source_label,
        mode: mode ?? "build",
        stack,
        context: neighbours.length ? renderContext(neighbours) : void 0
      });
      const prompt = String(res.prompt ?? "").trim();
      if (!prompt) return errorResult("Couldn't build anything from that idea.");
      return jsonResult({
        prompt,
        // Cite what it was built from, so the caller can show its working
        // rather than presenting the brief as having appeared from nowhere.
        built_from: {
          idea_id,
          title: data.title,
          mode: mode ?? "build",
          source_url: data.source_url ?? null,
          source_label: data.source_label ?? null,
          used_summary: Boolean(data.ai_summary),
          used_transcript: Boolean(data.extracted_text),
          used_stack: Boolean(stack?.trim()),
          context_ideas: neighbours.map((n) => ({ id: n.id, title: n.title }))
        }
      });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "Couldn't build a prompt");
    }
  }
});

// src/lib/mcp/tools/capture-url.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z3 } from "npm:zod@^3.25.76";
var capture_url_default = defineTool3({
  name: "capture_url",
  title: "Capture a URL",
  description: "Fetch a web page, extract its readable text, summarize it, and save the result as an idea in the vault. Use this when the user shares a link they want kept.",
  inputSchema: {
    url: z3.string().url().describe("Public http(s) URL to capture."),
    folder_id: z3.string().uuid().optional().describe("Folder to file the capture under."),
    note: z3.string().trim().max(2e3).optional().describe("The user's own note about why this matters."),
    save: z3.boolean().optional().describe("Save to the vault. Default true; pass false to preview only.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async ({ url, folder_id, note, save }, ctx) => {
    try {
      const userId = requireAuth(ctx);
      const extracted = await callFunction(
        ctx,
        "extract-url",
        { url }
      );
      const text = String(extracted.text ?? "").trim();
      if (!text) return errorResult("Could not extract readable text from that URL.");
      let summary = null;
      let suggestedTitle = null;
      try {
        const s = await callFunction(ctx, "summarize", {
          text,
          kind: "webpage",
          userNote: note ?? ""
        });
        summary = s.summary ?? null;
        suggestedTitle = s.suggestedTitle ?? null;
      } catch {
      }
      const title = String(extracted.title ?? suggestedTitle ?? url).slice(0, 200);
      if (save === false) {
        return jsonResult({ saved: false, title, summary, extracted_text: text.slice(0, 4e3), source_url: url });
      }
      const supabase = supabaseForUser(ctx);
      const { data, error } = await supabase.from("ideas").insert({
        user_id: userId,
        title,
        raw_note: note ?? null,
        extracted_text: text,
        ai_summary: summary,
        source_url: url,
        source_type: "webpage",
        source_label: extracted.siteName ?? null,
        folder_id: folder_id ?? null
      }).select("id, title, ai_summary, source_url, folder_id, created_at").maybeSingle();
      if (error) return errorResult(error.message);
      return jsonResult({ saved: true, idea: data });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "Capture failed");
    }
  }
});

// src/lib/mcp/tools/create-calendar-event.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z4 } from "npm:zod@^3.25.76";
var create_calendar_event_default = defineTool4({
  name: "create_calendar_event",
  title: "Create calendar event",
  description: "Save a birthday, anniversary or other recurring date the user wants remembered.",
  inputSchema: {
    name: z4.string().trim().min(1).max(120).describe("Who or what the date is for."),
    event_type: z4.string().trim().min(1).max(40).describe("For example birthday, anniversary, holiday."),
    month: z4.number().int().min(1).max(12).optional(),
    day: z4.number().int().min(1).max(31).optional(),
    birth_year: z4.number().int().min(1900).max(2200).optional(),
    emoji: z4.string().trim().max(8).optional(),
    notes: z4.string().trim().max(2e3).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    try {
      const userId = requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const { data, error } = await supabase.from("calendar_events").insert({
        user_id: userId,
        name: input.name,
        event_type: input.event_type,
        month: input.month ?? null,
        day: input.day ?? null,
        birth_year: input.birth_year ?? null,
        emoji: input.emoji ?? null,
        notes: input.notes ?? null
      }).select().maybeSingle();
      if (error) return errorResult(error.message);
      return jsonResult({ event: data });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "Create failed");
    }
  }
});

// src/lib/mcp/tools/create-folder.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z5 } from "npm:zod@^3.25.76";
var create_folder_default = defineTool5({
  name: "create_folder",
  title: "Create folder",
  description: "Create a new folder in the vault. Reuses the existing folder when the name already exists.",
  inputSchema: { name: z5.string().trim().min(1).max(80) },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name }, ctx) => {
    try {
      const userId = requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const { data: existing } = await supabase.from("folders").select("id, name").ilike("name", name).maybeSingle();
      if (existing) return jsonResult({ folder: existing, created: false });
      const { data, error } = await supabase.from("folders").insert({ user_id: userId, name }).select("id, name, created_at").maybeSingle();
      if (error) return errorResult(error.message);
      return jsonResult({ folder: data, created: true });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "Create failed");
    }
  }
});

// src/lib/mcp/tools/create-idea.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z6 } from "npm:zod@^3.25.76";
var SOURCE_TYPES = ["manual", "webpage", "transcript", "audio", "youtube", "instagram", "tiktok"];
var create_idea_default = defineTool6({
  name: "create_idea",
  title: "Create idea",
  description: "Save a new idea, note or captured text into the user's second brain. Use this whenever the user wants something remembered.",
  inputSchema: {
    title: z6.string().trim().min(1).max(200).describe("Short title for the idea."),
    note: z6.string().trim().optional().describe("The note body / raw text to store verbatim."),
    summary: z6.string().trim().optional().describe("Optional summary of the note."),
    folder_id: z6.string().uuid().optional().describe("Folder to file it under."),
    tags: z6.array(z6.string().trim().min(1)).max(12).optional().describe("Tags for retrieval."),
    source_url: z6.string().url().optional().describe("Where the idea came from, if any."),
    source_type: z6.enum(SOURCE_TYPES).optional().describe("Capture path. Default manual."),
    priority: z6.enum(["none", "low", "medium", "high"]).optional(),
    is_favorite: z6.boolean().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    try {
      const userId = requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const { data, error } = await supabase.from("ideas").insert({
        user_id: userId,
        title: input.title,
        raw_note: input.note ?? null,
        ai_summary: input.summary ?? null,
        folder_id: input.folder_id ?? null,
        tags: input.tags ?? [],
        source_url: input.source_url ?? null,
        source_type: input.source_type ?? "manual",
        priority: input.priority ?? "none",
        is_favorite: input.is_favorite ?? false
      }).select().maybeSingle();
      if (error) return errorResult(error.message);
      return jsonResult({ idea: data });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "Create failed");
    }
  }
});

// src/lib/mcp/tools/create-todo.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z7 } from "npm:zod@^3.25.76";
var create_todo_default = defineTool7({
  name: "create_todo",
  title: "Create todo",
  description: "Add a todo to the user's list, with an optional due date.",
  inputSchema: {
    title: z7.string().trim().min(1).max(200),
    due_at: z7.string().datetime().optional().describe("ISO 8601 due timestamp.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, due_at }, ctx) => {
    try {
      const userId = requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const { data, error } = await supabase.from("todos").insert({ user_id: userId, title, due_at: due_at ?? null }).select("id, title, done, due_at, created_at").maybeSingle();
      if (error) return errorResult(error.message);
      return jsonResult({ todo: data });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "Create failed");
    }
  }
});

// src/lib/mcp/tools/delete-idea.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z8 } from "npm:zod@^3.25.76";
var delete_idea_default = defineTool8({
  name: "delete_idea",
  title: "Delete idea",
  description: "Move one idea to the user's Trash. It stops being searchable and any share links for it are revoked, but it stays recoverable for 30 days. Confirm with the user before calling this.",
  inputSchema: { idea_id: z8.string().uuid() },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ idea_id }, ctx) => {
    try {
      requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const { error } = await supabase.from("ideas").update({ deleted_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", idea_id).is("deleted_at", null);
      if (error) return errorResult(error.message);
      return textResult(
        `Moved idea ${idea_id} to Trash. It can be restored from Trash in the app for 30 days.`
      );
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "Delete failed");
    }
  }
});

// src/lib/mcp/tools/get-idea.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z9 } from "npm:zod@^3.25.76";
var get_idea_default = defineTool9({
  name: "get_idea",
  title: "Get idea",
  description: "Read one saved idea in full: note body, AI summary, extracted source text, generated prompt, tags, folder and linked references.",
  inputSchema: {
    idea_id: z9.string().uuid().describe("The idea id."),
    include_references: z9.boolean().optional().describe("Also return auto-extracted reference links. Default true.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ idea_id, include_references }, ctx) => {
    try {
      requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const { data, error } = await supabase.from("ideas").select("*").eq("id", idea_id).is("deleted_at", null).maybeSingle();
      if (error) return errorResult(error.message);
      if (!data) return errorResult("Idea not found");
      let folderName = null;
      if (data.folder_id) {
        const { data: folder } = await supabase.from("folders").select("name").eq("id", data.folder_id).maybeSingle();
        folderName = folder?.name ?? null;
      }
      let references = [];
      if (include_references !== false) {
        const { data: refs } = await supabase.from("idea_references").select("*").eq("idea_id", idea_id);
        references = refs ?? [];
      }
      return jsonResult({ idea: { ...data, folder_name: folderName }, references });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "Read failed");
    }
  }
});

// src/lib/mcp/tools/get-idea-chat.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z10 } from "npm:zod@^3.25.76";
var get_idea_chat_default = defineTool10({
  name: "get_idea_chat",
  title: "Get idea brainstorm history",
  description: "Read the saved brainstorm conversation attached to one idea, so you can continue the user's earlier thinking instead of starting over.",
  inputSchema: {
    idea_id: z10.string().uuid(),
    limit: z10.number().int().min(1).max(200).optional().describe("Max messages, default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ idea_id, limit }, ctx) => {
    try {
      requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const { data, error } = await supabase.from("idea_chats").select("role, content, created_at").eq("idea_id", idea_id).order("created_at", { ascending: true }).limit(limit ?? 50);
      if (error) return errorResult(error.message);
      return jsonResult({ idea_id, messages: data ?? [] });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "Read failed");
    }
  }
});

// src/lib/mcp/tools/get-instructions.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@1.0.0";
var get_instructions_default = defineTool11({
  name: "get_instructions",
  title: "Get personal instructions",
  description: "Read the user's standing personal instructions for how their second brain should behave (general style, capture, summarizing, tagging, organizing). Call this first in a new session and follow the rules it returns.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    try {
      requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const { data, error } = await supabase.from("user_instructions").select("general, capture, summarize, tagging, organizing, updated_at").maybeSingle();
      if (error) return errorResult(error.message);
      return jsonResult({
        instructions: data ?? { general: "", capture: "", summarize: "", tagging: "", organizing: "", updated_at: null },
        has_instructions: Boolean(data)
      });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "Read failed");
    }
  }
});

// src/lib/mcp/tools/list-calendar-events.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z11 } from "npm:zod@^3.25.76";
var list_calendar_events_default = defineTool12({
  name: "list_calendar_events",
  title: "List calendar events",
  description: "List the user's saved dates: birthdays, anniversaries and other recurring events, optionally filtered to one month.",
  inputSchema: {
    month: z11.number().int().min(1).max(12).optional().describe("Filter to a calendar month (1-12).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ month }, ctx) => {
    try {
      requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      let q = supabase.from("calendar_events").select("id, name, event_type, month, day, birth_year, emoji, notes, floating_key").order("month").order("day");
      if (month) q = q.eq("month", month);
      const { data, error } = await q;
      if (error) return errorResult(error.message);
      return jsonResult({ count: data?.length ?? 0, events: data ?? [] });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "List failed");
    }
  }
});

// src/lib/mcp/tools/list-folders.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@1.0.0";
var list_folders_default = defineTool13({
  name: "list_folders",
  title: "List folders",
  description: "List the user's vault folders with idea counts, so you can file new ideas in the right place.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    try {
      requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const [{ data: folders, error }, { data: ideas }] = await Promise.all([
        supabase.from("folders").select("id, name, created_at").order("name"),
        supabase.from("ideas").select("folder_id")
      ]);
      if (error) return errorResult(error.message);
      const counts = /* @__PURE__ */ new Map();
      for (const row of ideas ?? []) {
        const key = String(row.folder_id ?? "");
        if (key) counts.set(key, (counts.get(key) ?? 0) + 1);
      }
      return jsonResult({
        folders: (folders ?? []).map((f) => ({ ...f, idea_count: counts.get(String(f.id)) ?? 0 })),
        unfiled_count: (ideas ?? []).filter((r) => !r.folder_id).length
      });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "List failed");
    }
  }
});

// src/lib/mcp/tools/list-tags.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@1.0.0";
var list_tags_default = defineTool14({
  name: "list_tags",
  title: "List tags",
  description: "List every tag used in the vault with its frequency. Use it to reuse the user's own vocabulary instead of inventing new tags.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    try {
      requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const { data, error } = await supabase.from("ideas").select("tags").is("deleted_at", null).order("updated_at", { ascending: false }).limit(2e3);
      if (error) return errorResult(error.message);
      const counts = /* @__PURE__ */ new Map();
      for (const row of data ?? []) {
        for (const tag of Array.isArray(row.tags) ? row.tags : []) {
          const key = String(tag).trim();
          if (key) counts.set(key, (counts.get(key) ?? 0) + 1);
        }
      }
      const tags = [...counts.entries()].sort((a, b) => b[1] - a[1]).map(([tag, count]) => ({ tag, count }));
      return jsonResult({ tags });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "List failed");
    }
  }
});

// src/lib/mcp/tools/list-todos.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z12 } from "npm:zod@^3.25.76";
var list_todos_default = defineTool15({
  name: "list_todos",
  title: "List todos",
  description: "List the user's todos, newest first. Defaults to open items only.",
  inputSchema: {
    include_done: z12.boolean().optional().describe("Include completed todos. Default false."),
    limit: z12.number().int().min(1).max(100).optional().describe("Max results, default 30.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_done, limit }, ctx) => {
    try {
      requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      let q = supabase.from("todos").select("id, title, done, due_at, completed_at, created_at").order("created_at", { ascending: false }).limit(limit ?? 30);
      if (!include_done) q = q.eq("done", false);
      const { data, error } = await q;
      if (error) return errorResult(error.message);
      return jsonResult({ count: data?.length ?? 0, todos: data ?? [] });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "List failed");
    }
  }
});

// src/lib/mcp/tools/recall-context.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z13 } from "npm:zod@^3.25.76";
var STOP = /* @__PURE__ */ new Set([
  "the",
  "and",
  "for",
  "with",
  "that",
  "this",
  "from",
  "have",
  "has",
  "was",
  "were",
  "are",
  "you",
  "your",
  "about",
  "into",
  "what",
  "when",
  "how",
  "why",
  "can",
  "will",
  "any",
  "all",
  "not",
  "but"
]);
var terms = (q) => [...new Set(q.toLowerCase().split(/[^a-z0-9]+/).filter((t) => t.length > 2 && !STOP.has(t)))];
var snippet = (text, keys) => {
  const flat = text.replace(/\s+/g, " ").trim();
  const lower = flat.toLowerCase();
  const hit = keys.map((k) => lower.indexOf(k)).filter((i) => i >= 0).sort((a, b) => a - b)[0] ?? 0;
  const start = Math.max(0, hit - 120);
  return (start > 0 ? "\u2026" : "") + flat.slice(start, start + 360) + (flat.length > start + 360 ? "\u2026" : "");
};
var recall_context_default = defineTool16({
  name: "recall_context",
  title: "Recall second-brain context",
  description: "The main second-brain retrieval tool. Given a question or topic, returns the user's personal instructions plus the most relevant saved ideas as ranked snippets with the reason each was picked. Call this before answering questions that depend on what the user already knows or decided.",
  inputSchema: {
    query: z13.string().trim().min(2).describe("The question or topic you need the user's own context for."),
    limit: z13.number().int().min(1).max(15).optional().describe("Max snippets, default 6.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    try {
      requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const keys = terms(query);
      const [{ data: rows, error }, { data: instructions }, { data: folders }] = await Promise.all([
        supabase.from("ideas").select("id, title, raw_note, ai_summary, extracted_text, tags, folder_id, updated_at").is("deleted_at", null).order("updated_at", { ascending: false }).limit(300),
        supabase.from("user_instructions").select("general, capture, summarize, tagging, organizing").maybeSingle(),
        supabase.from("folders").select("id, name")
      ]);
      if (error) return errorResult(error.message);
      const folderNames = new Map((folders ?? []).map((f) => [String(f.id), String(f.name)]));
      const now = Date.now();
      const scored = (rows ?? []).map((r) => {
        const row = r;
        const haystack = [row.title, row.ai_summary, row.raw_note, row.extracted_text, (row.tags ?? []).join(" ")].filter(Boolean).join("\n");
        const lower = haystack.toLowerCase();
        const matched = keys.filter((k) => lower.includes(k));
        let score = matched.length * 3;
        if (row.title && keys.some((k) => row.title.toLowerCase().includes(k))) score += 4;
        if ((row.tags ?? []).some((t) => keys.includes(String(t).toLowerCase()))) score += 3;
        const ageDays = (now - new Date(row.updated_at).getTime()) / 864e5;
        score += Math.max(0, 2 - ageDays / 45);
        return { row, score, matched, haystack };
      }).filter((s) => s.matched.length > 0).sort((a, b) => b.score - a.score).slice(0, limit ?? 6);
      return jsonResult({
        query,
        instructions: instructions ?? null,
        hits: scored.map(({ row, score, matched, haystack }) => ({
          idea_id: row.id,
          title: row.title,
          folder: row.folder_id ? folderNames.get(String(row.folder_id)) ?? null : null,
          tags: row.tags ?? [],
          updated_at: row.updated_at,
          score: Math.round(score * 100) / 100,
          why_selected: `matched: ${matched.join(", ")}`,
          snippet: snippet(haystack, matched)
        }))
      });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "Recall failed");
    }
  }
});

// src/lib/mcp/tools/search-ideas.ts
import { defineTool as defineTool17 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z14 } from "npm:zod@^3.25.76";
var search_ideas_default = defineTool17({
  name: "search_ideas",
  title: "Search ideas",
  description: "Search the signed-in user's second brain for saved ideas and notes. Matches title, note body, summary and extracted text. Use this before answering anything about what the user has already captured.",
  inputSchema: {
    query: z14.string().trim().optional().describe("Free-text search. Omit to list the most recent ideas."),
    folder_id: z14.string().uuid().optional().describe("Restrict results to one folder."),
    tag: z14.string().trim().optional().describe("Restrict results to ideas carrying this tag."),
    favorites_only: z14.boolean().optional().describe("Only return favorited ideas."),
    limit: z14.number().int().min(1).max(50).optional().describe("Max results, default 15.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, folder_id, tag, favorites_only, limit }, ctx) => {
    try {
      requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      let q = supabase.from("ideas").select("id, title, ai_summary, raw_note, tags, folder_id, source_type, source_url, is_favorite, priority, created_at, updated_at").is("deleted_at", null).order("updated_at", { ascending: false }).limit(limit ?? 15);
      if (folder_id) q = q.eq("folder_id", folder_id);
      if (favorites_only) q = q.eq("is_favorite", true);
      if (tag) q = q.contains("tags", [tag]);
      if (query) {
        const safe = query.replace(/[%,()]/g, " ").trim();
        if (safe) {
          q = q.or(
            ["title", "raw_note", "ai_summary", "extracted_text"].map((c) => `${c}.ilike.%${safe}%`).join(",")
          );
        }
      }
      const { data, error } = await q;
      if (error) return errorResult(error.message);
      return jsonResult({ count: data?.length ?? 0, ideas: data ?? [] });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "Search failed");
    }
  }
});

// src/lib/mcp/tools/set-todo-done.ts
import { defineTool as defineTool18 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z15 } from "npm:zod@^3.25.76";
var set_todo_done_default = defineTool18({
  name: "set_todo_done",
  title: "Complete or reopen todo",
  description: "Mark a todo complete, or reopen it by passing done=false.",
  inputSchema: {
    todo_id: z15.string().uuid(),
    done: z15.boolean().optional().describe("Default true.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ todo_id, done }, ctx) => {
    try {
      requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const isDone = done !== false;
      const { data, error } = await supabase.from("todos").update({
        done: isDone,
        completed_at: isDone ? (/* @__PURE__ */ new Date()).toISOString() : null,
        updated_at: (/* @__PURE__ */ new Date()).toISOString()
      }).eq("id", todo_id).select("id, title, done, completed_at").maybeSingle();
      if (error) return errorResult(error.message);
      if (!data) return errorResult("Todo not found");
      return jsonResult({ todo: data });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "Update failed");
    }
  }
});

// src/lib/mcp/tools/summarize-text.ts
import { defineTool as defineTool19 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z16 } from "npm:zod@^3.25.76";
var summarize_text_default = defineTool19({
  name: "summarize_text",
  title: "Summarize text",
  description: "Summarize a transcript or long passage using the user's own summarizing rules. Returns the summary and a suggested title without saving anything.",
  inputSchema: {
    text: z16.string().trim().min(40).describe("The transcript or passage to summarize."),
    kind: z16.enum(["manual", "webpage", "transcript", "audio"]).optional().describe("Content kind. Default transcript."),
    note: z16.string().trim().max(2e3).optional().describe("The user's framing or question about the text.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ text, kind, note }, ctx) => {
    try {
      requireAuth(ctx);
      const res = await callFunction(ctx, "summarize", {
        text,
        kind: kind ?? "transcript",
        userNote: note ?? ""
      });
      return jsonResult({ summary: res.summary ?? "", suggested_title: res.suggestedTitle ?? null });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "Summarize failed");
    }
  }
});

// src/lib/mcp/tools/update-idea.ts
import { defineTool as defineTool20 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z17 } from "npm:zod@^3.25.76";
var update_idea_default = defineTool20({
  name: "update_idea",
  title: "Update idea",
  description: "Edit an existing idea: retitle it, rewrite the note, set the summary or generated prompt, move folders, change tags, priority or favorite state. Only the fields you pass change.",
  inputSchema: {
    idea_id: z17.string().uuid(),
    title: z17.string().trim().min(1).max(200).optional(),
    note: z17.string().trim().optional().describe("Replaces raw_note."),
    summary: z17.string().trim().optional(),
    generated_prompt: z17.string().trim().optional().describe("Reusable AI prompt derived from the idea."),
    folder_id: z17.string().uuid().nullable().optional(),
    tags: z17.array(z17.string().trim().min(1)).max(12).optional(),
    priority: z17.enum(["none", "low", "medium", "high"]).optional(),
    is_favorite: z17.boolean().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ idea_id, note, summary, ...rest }, ctx) => {
    try {
      requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const patch = { ...rest };
      if (note !== void 0) patch.raw_note = note;
      if (summary !== void 0) patch.ai_summary = summary;
      if (Object.keys(patch).length === 0) return errorResult("Nothing to update");
      patch.updated_at = (/* @__PURE__ */ new Date()).toISOString();
      const { data, error } = await supabase.from("ideas").update(patch).eq("id", idea_id).select().maybeSingle();
      if (error) return errorResult(error.message);
      if (!data) return errorResult("Idea not found");
      return jsonResult({ idea: data });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "Update failed");
    }
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool21 } from "npm:@lovable.dev/mcp-js@1.0.0";
var whoami_default = defineTool21({
  name: "whoami",
  title: "Who am I",
  description: "Confirm which vault account this connection is acting as, plus a quick size summary of the vault. Useful for verifying the connection works.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    try {
      if (!ctx.isAuthenticated()) return jsonResult({ authenticated: false });
      const supabase = supabaseForUser(ctx);
      const [{ count: ideaCount }, { count: folderCount }, { count: todoCount }] = await Promise.all([
        supabase.from("ideas").select("id", { count: "exact", head: true }),
        supabase.from("folders").select("id", { count: "exact", head: true }),
        supabase.from("todos").select("id", { count: "exact", head: true })
      ]);
      return jsonResult({
        authenticated: true,
        user_id: ctx.getUserId(),
        email: ctx.getUserEmail() ?? null,
        vault: { ideas: ideaCount ?? 0, folders: folderCount ?? 0, todos: todoCount ?? 0 }
      });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "Lookup failed");
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "uwuhfvhqnpozhndrabwl";
var mcp_default = defineMcp({
  name: "fartbrains-app",
  title: "Fartbrains.app",
  version: "0.1.0",
  instructions: [
    "This is the signed-in user's personal second brain: saved ideas, notes, captured links and transcripts, folders, tags, todos and important dates.",
    "Start a session with `get_instructions` and follow the user's standing rules, then use `recall_context` before answering anything that depends on what they already captured or decided.",
    "Use `search_ideas` / `get_idea` to read, `create_idea` and `capture_url` to save new material, `update_idea` to refine, and `create_todo` for actions.",
    "When the user wants to build, spec or act on something they saved rather than just read it, call `build_prompt` \u2014 it turns a saved idea or transcript into a brief you can work from. You do the building; this vault supplies the material and the brief.",
    "Reuse the user's existing folders and tags (`list_folders`, `list_tags`) instead of inventing new vocabulary. Confirm before calling `delete_idea`."
  ].join(" "),
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    get_instructions_default,
    recall_context_default,
    search_ideas_default,
    get_idea_default,
    create_idea_default,
    update_idea_default,
    delete_idea_default,
    capture_url_default,
    summarize_text_default,
    build_prompt_default,
    list_folders_default,
    create_folder_default,
    list_tags_default,
    list_todos_default,
    create_todo_default,
    set_todo_done_default,
    list_calendar_events_default,
    create_calendar_event_default,
    get_idea_chat_default,
    append_idea_chat_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@1.0.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
